// <auto-generated />
using System;
using APIQuanLyKhachSan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIQuanLyKhachSan.Migrations
{
    [DbContext(typeof(DbQuanLyKhachSanContext))]
    [Migration("20240110024639_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIQuanLyKhachSan.Models.AnhQuangCao", b =>
                {
                    b.Property<string>("IdAnh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UrlImageQc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlImageQC");

                    b.HasKey("IdAnh");

                    b.ToTable("AnhQuangCao");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.Blog", b =>
                {
                    b.Property<string>("IdBlog")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tieude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBlog");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.ChiTietPhong", b =>
                {
                    b.Property<string>("IdPhong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DienTich")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.HasKey("IdPhong");

                    b.ToTable("ChiTietPhong");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.DanhGium", b =>
                {
                    b.Property<string>("IdHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdNguoiDung")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDon");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.Property<string>("IdHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GioCheckin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("GioCheckout")
                        .HasColumnType("datetime");

                    b.Property<string>("IdNguoiDung")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdPhong")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("PhuThu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int?>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UrlImages")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Vat")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("VAT");

                    b.Property<string>("YeuCau")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdHoaDon");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.NguoiDung", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IdQuyen")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.Phong", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaSauGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("IdLoaiPhong")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.ThongBao", b =>
                {
                    b.Property<string>("TenThongBao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Tttb")
                        .HasColumnType("int");

                    b.HasKey("TenThongBao");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.ThongTinWeb", b =>
                {
                    b.Property<string>("LoaiThongTin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImages")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiThongTin");

                    b.ToTable("ThongTinWeb");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.TuVan", b =>
                {
                    b.Property<string>("IdTuVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayGioNhan")
                        .HasColumnType("datetime");

                    b.Property<string>("Ten")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdTuVan");

                    b.ToTable("TuVan");
                });

            modelBuilder.Entity("APIQuanLyKhachSan.Models.XacThuc", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaXacThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNguoiDung");

                    b.ToTable("XacThuc");
                });
#pragma warning restore 612, 618
        }
    }
}
